root: true
env:
  es6: true
  node: true
  mocha: true
extends: 'eslint:recommended'
rules:
  indent:
    - error
    - 2
  brace-style:
    - error
    - stroustrup
  linebreak-style:
    - error
    - unix

  semi:
    - error
    - always

  quotes:
    - off
  no-console:
    - off
